/**
 * Version              Date                Name                Description
 * *******************************************************************************
 * 1.0                  2026-03-22          Dev1                Added Add Method
 *
 */
public with sharing class Calculator {
    public Calculator() {

    }

    public Integer add(Integer a, Integer b) {
        return a + b;
    }

}